INSERT INTO MOVIE (ID,BUDGET,CASTS,CATEGORY,MOVIE_NAME,RELEASE_DATE)
VALUES (1, 1000, 'TONY STARK', 'ACTION','AVENGERS','10-10-2011');
INSERT INTO MOVIE (ID,BUDGET,CASTS,CATEGORY,MOVIE_NAME,RELEASE_DATE)
VALUES (2, 2000, 'CAPTION AMERICA', 'ACTION','AVENGERS2','10-10-2015');
INSERT INTO MOVIE (ID,BUDGET,CASTS,CATEGORY,MOVIE_NAME,RELEASE_DATE)
VALUES (3, 3000, 'BLACK WIDOW', 'ACTION','AVENGERS','10-10-2019');